apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-sa
  annotations:
    azure.workload.identity/client-id: <USER_ASSIGNED_CLIENT_ID>
    azure.workload.identity/tenant-id: <IDENTITY_TENANT>
